version: 2
updates:
  # Go Modules
  - package-ecosystem: "gomod"
    directory: "/backend" 
    schedule:
      interval: "weekly"

  # Angular (npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"


  # Optional: GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

