name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    env:
      GO_VERSION: "1.23.4"
      NODE_VERSION: "22"

    steps:
      - name: Checkout code && Setup Go
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npx ng build
          cd ..
          cp -r frontend/dist/frontend/browser backend/cmd/strichliste/frontendDist

      - name: Test Code
        run: |
          cd backend
          go test ./...
    
      - name: Check Code format
        run: |
          files=$(gofmt -l ./backend) && [ -z "$files" ]
          if [ -n "$files" ]; then
          echo "formatting_error=true" >> $GITHUB_ENV
          echo "files=$files" >> $GITHUB_ENV
          else
            echo "formatting_error=false" >> $GITHUB_ENV
          fi

      - name: Comment on PR if format is incorrect
        if: ${{ github.event_name == 'pull_request' && env.formatting_error == 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            const files = process.env.files.split("\n").filter(f => f);
            const body = `
              ## :warning: Code Formatting Issue Detected
              The following files need formatting:
              \`\`\`
              ${files.join("\n")}
              \`\`\`
              Please run \`gofmt\` to fix these issues.
            `;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });

