name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    env:
      GO_VERSION: "1.23.4"
      NODE_VERSION: "22"

    steps:
      - name: Checkout code && Setup Go
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npx ng build
          cp -r frontend/dist/frontend/browser backend/cmd/strichliste/frontendDist

      - name: Test Code
        run: |
          cd backend
          go run ./...
    
      - name: Check Code format
        run: files=$(gofmt -l ./backend) && [ -z "$files" ]
