name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    env:
      GO_VERSION: "1.23.4"
      NODE_VERSION: "22"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check Code format
        id: check_format
        run: |
          files=$(gofmt -l ./backend)
          if [ -n "$files" ]; then
            echo "The following files are not formatted correctly:"
            echo "$files"
            exit 1
          else
            echo "All files are correctly formatted."
          fi

      - name: Build Frontend
        run: |
          cd frontend
          npm ci
          npx ng build
          cd ..
          cp -r frontend/dist/frontend/browser backend/cmd/strichliste/frontendDist

      - name: Test Code
        run: |
          cd backend
          go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html

      - uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: backend/coverage.html

      - name: Setup SSH
        run: |
          # setup / start ssh auth socket which manages our ssh keys when connecting to other servers via ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          # load the private key
          mkdir ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: Push report to server
        run: scp backend/coverage.html group6@dhbw.hoenle.xyz:/var/www/group6/test-coverage.html

      - name: Comment on PR if format is incorrect
        if: ${{ github.event_name == 'pull_request' && failure() }}
        uses: actions/github-script@v6
        with:
          script: |
            const files = process.env.files ? process.env.files.split("\n").filter(f => f) : [];
            if (files.length === 0) {
              core.warning("No files to format. Skipping PR comment.");
              return;
            }
            const body = `
              ## :warning: Code Formatting Issue Detected
              The following files need formatting:
              \`\`\`
              ${files.join("\n")}
              \`\`\`
              Please run \`gofmt\` to fix these issues.
            `;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
  
